### ISSUE TITLE
Error while installing miscellaneous-pal

### ISSUE THREAD

**Issue by omi-kron** [DreamVu/PAL-USB#9]
Ubuntu - 18.04
Cuda - 10.2
tensorrt - 7.0.0

Followed method 1 for installing the package

After running chmod +x pal && ./pal and while installing miscellaneous-pal

We got 

Exception:
Traceback (most recent call last):
  File "/home/om/DreamVu/dreamvu_ws/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/om/DreamVu/dreamvu_ws/lib/python3.6/site-packages/pip/commands/install.py", line 290, in run
    with self._build_session(options) as session:
  File "/home/om/DreamVu/dreamvu_ws/lib/python3.6/site-packages/pip/basecommand.py", line 69, in _build_session
    if options.cache_dir else None
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int

![Screenshot from 2022-09-25 16-15-47](https://user-images.githubusercontent.com/75268314/192139639-87632ab3-69ba-47c7-aaba-faac1ba6dcb7.png)

**Comment by kishk31** [comment]
Hi Om,

Thanks for your patience.
Error is related to the OS itself.
Different solutions are available on the web, you can refer to those.
For reference: https://stackoverflow.com/questions/54555927/typeerror-expected-str-bytes-or-os-pathlike-object-not-set-error-scrapy
